name: anbang
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2023.05.30=h06a4308_0
  - comm=0.1.2=py38h06a4308_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - importlib-metadata=6.0.0=py38h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - ipykernel=6.25.0=py38h2f386ee_0
  - ipython=8.12.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jupyter_client=8.1.0=py38h06a4308_0
  - jupyter_core=5.3.0=py38h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - openssl=3.0.10=h7f8727e_0
  - packaging=23.0=py38h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.2.1=py38h06a4308_0
  - platformdirs=2.5.2=py38h06a4308_0
  - prompt-toolkit=3.0.36=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - python=3.8.17=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=25.1.0=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.3.2=py38h5eee18b_0
  - traitlets=5.7.1=py38h06a4308_0
  - typing_extensions=4.7.1=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.23.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.13.36
      - aliyun-python-sdk-kms==2.16.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - bcrypt==4.0.1
      - beautifulsoup4==4.12.2
      - blessed==1.20.0
      - bs4==0.0.1
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.15.1
      - cfgv==3.4.0
      - charset-normalizer==3.2.0
      - click==8.1.7
      - colorama==0.4.6
      - colossalai==0.3.2
      - contexttimer==0.3.3
      - contourpy==1.1.0
      - crcmod==1.7
      - cryptography==41.0.3
      - cycler==0.11.0
      - dataclasses-json==0.6.0
      - datasets==2.14.5
      - datasketch==1.5.9
      - deprecated==1.2.14
      - dill==0.3.7
      - distlib==0.3.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - einops==0.6.1
      - exceptiongroup==1.1.3
      - fabric==3.2.2
      - fastapi==0.103.1
      - filelock==3.12.4
      - fonttools==4.42.0
      - frozendict==2.3.8
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - gpustat==1.1
      - greenlet==2.0.2
      - grpcio==1.58.0
      - huggingface-hub==0.17.2
      - identify==2.5.29
      - idna==3.4
      - importlib-resources==6.0.1
      - invoke==2.2.0
      - jmespath==0.10.0
      - jsonlines==3.1.0
      - jsonpatch==1.33
      - jsonpointer==2.4
      - kiwisolver==1.4.4
      - langchain==0.0.299
      - langsmith==0.0.40
      - loralib==0.1.2
      - lxml==4.9.3
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.20.1
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - networkx==3.1
      - ninja==1.11.1
      - nodeenv==1.8.0
      - numexpr==2.8.6
      - numpy==1.24.4
      - nvidia-ml-py==12.535.77
      - oauthlib==3.2.2
      - opendatalab==0.0.10
      - openxlab==0.0.19
      - oss2==2.17.0
      - pandas==2.0.3
      - paramiko==3.3.1
      - pathtools==0.1.2
      - pillow==10.0.0
      - pre-commit==3.4.0
      - protobuf==4.24.3
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pycryptodome==3.18.0
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pynacl==1.5.0
      - pyparsing==3.0.9
      - pytz==2023.3
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.4.2
      - rsa==4.9
      - safetensors==0.3.3
      - scipy==1.10.1
      - sentencepiece==0.1.99
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - setuptools==60.2.0
      - shtab==1.6.4
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - sqlalchemy==2.0.21
      - sse-starlette==1.6.5
      - starlette==0.27.0
      - tenacity==8.2.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - tokenizers==0.13.3
      - torch==1.12.1+cu113
      - torchaudio==0.12.1+cu113
      - torchvision==0.13.1+cu113
      - tqdm==4.65.0
      - transformers==4.33.2
      - trl==0.7.2.dev0
      - typing-inspect==0.9.0
      - tyro==0.5.7
      - tzdata==2023.3
      - urllib3==1.26.16
      - virtualenv==20.24.5
      - wandb==0.15.11
      - werkzeug==2.3.7
      - wrapt==1.15.0
      - xxhash==3.3.0
      - yarl==1.9.2
prefix: /home/lcyab/data/anaconda/envs/anbang
