name: Build

on: 
  pull_request:
    types: [synchronize, labeled]

jobs:
  build:
    name: Build and Test Colossal-AI
    if: |
        github.event.pull_request.draft == false &&
        github.base_ref == 'main' &&
        github.event.pull_request.base.repo.full_name == 'hpcaitech/ColossalAI' &&
        contains( github.event.pull_request.labels.*.name, 'Run Build and Test')
    runs-on: [self-hosted, gpu]
    container:
      image: frankleeeee/pytorch-cuda:1.10.1-11.3.0
      options: --gpus all --rm --ipc=host -v /data/scratch/cifar-10:/data/scratch/cifar-10
    timeout-minutes: 40
    steps:
      - name: Install dependencies
        run: |
          pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          pip install -U pip setuptools wheel --user
          pip install pytest tensorboard transformers
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_KEY_FOR_CI }}
      - name: Install Colossal-AI      
        run: |
          pip install -r requirements/requirements.txt
          pip install -v --no-cache-dir .
      - name: Unit Testing
        run: |
          PYTHONPATH=$PWD pytest tests
        env:
          DATA: /data/scratch/cifar-10
